name: pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  testing-and-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install dependencies
        run: npm install
        working-directory: hello-ci
      - name: Linting the code
        run: npm run lint
        working-directory: hello-ci
      - name: Testing the react components
        run: npm test
        working-directory: hello-ci
      - name: Abort pull request if tests fail
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Tests failed. Pull request aborted."
            exit 1
          fi
